"""
verifier.py — LLM-based verification for generated documentation.

Stage C of the two-stage verification pipeline.
Uses a separate LLM call to cross-check generated content against
verified facts extracted from source code.

Default verifier model: github/Phi-4 (good at fact-checking, cheap).
If the generator model IS Phi-4, falls back to github/gpt-4o-mini
to avoid same-model self-review.
"""

from __future__ import annotations

import json
import logging
import re

from ..facts import FactItem
from ..llm import LLMProvider, build_llm
from .ast_extractor import ASTSymbol

logger = logging.getLogger(__name__)

DEFAULT_VERIFIER_MODEL = "github/Phi-4"
FALLBACK_VERIFIER_MODEL = "github/gpt-4o-mini"


def verify_chapter(
    chapter_content: str,
    facts: list[FactItem],
    ast_symbols: dict[str, list[ASTSymbol]] | None,
    llm: LLMProvider,
    model: str | None = None,
) -> tuple[str, list[str]]:
    """Verify a documentation chapter against verified source code facts.

    Sends the chapter + facts to a verifier LLM that returns a JSON array
    of corrections. Then applies those corrections to the content.

    Args:
        chapter_content: The chapter markdown to verify.
        facts: Verified facts from source code.
        ast_symbols: AST symbols keyed by file path.
        llm: The generator LLM instance (used to detect model conflicts).
        model: Explicit verifier model override. If None, uses Phi-4
               (or gpt-4o-mini if generator is Phi-4).

    Returns:
        Tuple of (corrected_content, list_of_issues_found).
    """
    verifier_model = _resolve_verifier_model(model, llm.model)
    verifier_llm = build_llm(model=verifier_model)

    facts_text = _format_facts_for_verification(facts, ast_symbols)
    prompt = _build_verification_prompt(chapter_content, facts_text)

    try:
        raw_response = verifier_llm.complete(prompt)
        corrections = _parse_verification_response(raw_response)
        corrected, issues = _apply_verification_corrections(chapter_content, corrections)
        return corrected, issues
    except (RuntimeError, ValueError, KeyError) as e:
        # RuntimeError: LLM call failure; ValueError/KeyError: response parse errors
        logger.warning("Verification failed: %s — returning original content", e)
        return chapter_content, [f"Verification error: {e}"]


def _resolve_verifier_model(explicit_model: str | None, generator_model: str) -> str:
    """Pick the verifier model, avoiding same-model self-review."""
    if explicit_model:
        return explicit_model

    gen_lower = generator_model.lower()
    if "phi-4" in gen_lower or "phi4" in gen_lower:
        return FALLBACK_VERIFIER_MODEL

    return DEFAULT_VERIFIER_MODEL


def _format_facts_for_verification(
    facts: list[FactItem],
    ast_symbols: dict[str, list[ASTSymbol]] | None,
) -> str:
    """Format facts and AST symbols into a compact text block for the verifier."""
    sections: list[str] = []

    if facts:
        by_type: dict[str, list[FactItem]] = {}
        for f in facts:
            by_type.setdefault(f.fact_type, []).append(f)

        for fact_type, items in sorted(by_type.items()):
            lines = [f"### {fact_type.upper()}"]
            for item in items:
                lines.append(f"- {item.value} ({item.file}:{item.line})")
            sections.append("\n".join(lines))

    if ast_symbols:
        sym_lines = ["### KEY SYMBOLS"]
        count = 0
        for file_path, symbols in ast_symbols.items():
            for sym in symbols:
                if sym.kind in ("function", "method", "struct", "class", "interface", "type"):
                    sym_lines.append(f"- {sym.signature} ({file_path}:{sym.line})")
                    count += 1
                    if count >= 50:  # cap to avoid token explosion
                        break
            if count >= 50:
                break
        if count > 0:
            sections.append("\n".join(sym_lines))

    return "\n\n".join(sections) if sections else "(no facts available)"


def _build_verification_prompt(chapter_content: str, facts_text: str) -> str:
    """Build the verification prompt for the LLM."""
    return f"""You are a technical accuracy verifier. You have two inputs:
1. A documentation chapter (generated by another AI)
2. A set of VERIFIED FACTS extracted from the actual source code

Your job:
- Compare every claim in the chapter against the verified facts
- Flag any claim NOT supported by the facts
- Flag any important fact MISSING from the chapter
- Suggest specific corrections

VERIFIED FACTS:
{facts_text}

CHAPTER TO VERIFY:
{chapter_content}

Return ONLY a JSON array of corrections (no markdown fences, no explanation outside the array):
[
  {{"type": "wrong", "claim": "the wrong claim text", "correction": "what it should say", "evidence": "fact: ..."}},
  {{"type": "missing", "fact": "the missing fact", "suggestion": "add: ..."}},
  {{"type": "ok", "claim": "a verified claim"}}
]

Rules:
- Only flag claims you can PROVE are wrong using the facts above
- Do NOT flag stylistic issues or formatting
- Do NOT flag claims about concepts/patterns (only verifiable facts like ports, versions, endpoints, function names)
- If the chapter looks accurate, return: [{{"type": "ok", "claim": "chapter is accurate"}}]
- Return valid JSON only — no markdown code fences, no trailing text"""


def _parse_verification_response(raw: str) -> list[dict]:
    """Parse the LLM's JSON response, handling common formatting issues."""
    text = raw.strip()

    # Strip markdown code fences if present
    if text.startswith("```"):
        lines = text.split("\n")
        # Remove first and last lines if they're fences
        if lines[0].startswith("```"):
            lines = lines[1:]
        if lines and lines[-1].strip().startswith("```"):
            lines = lines[:-1]
        text = "\n".join(lines).strip()

    # Try direct parse
    try:
        result = json.loads(text)
        if isinstance(result, list):
            return result
        return []
    except json.JSONDecodeError:
        pass

    # Try to find a JSON array in the response
    match = re.search(r'\[.*\]', text, re.DOTALL)
    if match:
        try:
            result = json.loads(match.group(0))
            if isinstance(result, list):
                return result
        except json.JSONDecodeError:
            pass

    logger.warning("Could not parse verification response as JSON")
    return []


def _apply_verification_corrections(
    content: str,
    corrections: list[dict],
) -> tuple[str, list[str]]:
    """Apply corrections from the verifier to the chapter content.

    Only applies 'wrong' type corrections where we can find and replace
    the claim text. 'missing' corrections are logged as issues.

    Returns:
        Tuple of (corrected_content, list_of_human_readable_issues).
    """
    issues: list[str] = []

    for item in corrections:
        if not isinstance(item, dict):
            continue

        item_type = item.get("type", "")

        if item_type == "wrong":
            claim = item.get("claim", "")
            correction = item.get("correction", "")
            evidence = item.get("evidence", "")
            if claim and correction and claim in content:
                content = content.replace(claim, correction, 1)
                issues.append(
                    f"FIXED: '{claim}' → '{correction}' (evidence: {evidence})"
                )
            elif claim:
                issues.append(
                    f"FLAGGED (not auto-fixed): '{claim}' — should be: '{correction}' (evidence: {evidence})"
                )

        elif item_type == "missing":
            fact = item.get("fact", "")
            suggestion = item.get("suggestion", "")
            if fact:
                issues.append(f"MISSING: {fact} — {suggestion}")

        elif item_type == "ok":
            pass  # verified claim, no action needed

    return content, issues
