"""
RepoForge - Agnostic code analysis tool that generates SKILL.md and AGENT.md
files ready for use in Claude Code, OpenCode, Cursor, Codex, Gemini CLI, and
GitHub Copilot.
"""

from .adapters import (
    ALL_TARGETS,
    adapt_for_codex,
    adapt_for_copilot,
    adapt_for_cursor,
    adapt_for_gemini,
    resolve_targets,
)
from .compressor import (
    CompressionResult,
    SkillCompressor,
    compress_directory,
    compress_file,
)
from .coverage import (
    CoverageFile,
    CoverageReport,
    auto_detect_and_parse,
    detect_coverage_files,
    parse_cobertura,
    parse_coverage_py_json,
    parse_jacoco,
    parse_lcov,
    render_coverage_markdown,
)
from .cross_repo import (
    CrossRepoMatch,
    RepoEntry,
    cross_repo_results_to_json,
    format_cross_repo_results,
    format_registry_list,
    registry_add,
    registry_build,
    registry_list,
    registry_remove,
    registry_search,
)
from .deep_analysis import (
    ASTNode,
    CallEdgeInfo,
    CFGNode,
    DFGEdge,
    FileAnalysis,
    FunctionAnalysis,
    PDGEdge,
    RepoAnalysis,
    analyze_file,
    analyze_repo,
    format_analysis,
)
from .dep_health import (
    DependencyHealthReport,
    DuplicateDep,
    LicenseConflict,
    OutdatedDep,
    analyze_dependency_health,
)
from .diagrams import (
    generate_all_diagrams,
    generate_call_flow_diagram,
    generate_dependency_diagram,
    generate_directory_diagram,
    generate_erd_diagram,
    generate_k8s_diagram,
    generate_openapi_diagram,
)
from .diff import (
    DiffEntry,
    DiffResult,
    diff_entities,
)
from .disclosure import (
    build_discovery_index,
    count_tier_markers,
    estimate_tokens,
    extract_frontmatter,
    extract_tier,
    has_tier_markers,
)
from .docs_generator import generate_docs
from .exporter import export_llm_view
from .generator import generate_artifacts
from .graph import (
    BlastRadiusResult,
    CodeGraph,
    Edge,
    Node,
    build_graph,
    build_graph_from_workspace,
    build_graph_v2,
    get_blast_radius_v2,
    is_test_file,
)
from .graph_query import (
    QueryResult,
    query_callees,
    query_callers,
    query_imports,
)
from .import_docs import (
    fetch_github_docs,
    fetch_npm_readme,
    fetch_pypi_description,
    import_docs,
)
from .incremental import (
    ChapterEntry,
    Manifest,
    build_chapter_deps,
    get_changed_files,
    get_stale_chapters,
    load_manifest,
    save_manifest,
)
from .plugins import (
    Command,
    PluginManifest,
    build_commands,
    build_plugin_manifest,
    commands_prompt,
    manifest_to_json,
    manifest_to_markdown,
    write_plugin,
)
from .prompts_cmd import (
    PROMPT_TYPES,
    AnalysisPrompt,
    generate_prompts,
    render_prompts_markdown,
    write_individual_prompts,
)
from .scorer import SkillScore, SkillScorer
from .security import (
    Finding,
    ScanResult,
    SecurityScanner,
    Severity,
    scan_generated_output,
)
from .semantic_search import (
    BehaviorIndex,
    BehaviorMatch,
    build_behavior_index,
    format_search_results,
)
from .semantic_search import (
    search_repo as search_by_behavior,
)
from .server import serve_docs, serve_skills
from .watch import FileWatcher, WatchEvent, watch_docs

__version__ = "0.4.0"
__all__ = [
    "DiffEntry",
    "DiffResult",
    "diff_entities",
    "generate_artifacts",
    "generate_docs",
    "export_llm_view",
    "serve_docs",
    "serve_skills",
    "SkillScorer",
    "SkillScore",
    "adapt_for_cursor",
    "adapt_for_codex",
    "adapt_for_gemini",
    "adapt_for_copilot",
    "resolve_targets",
    "ALL_TARGETS",
    "extract_tier",
    "extract_frontmatter",
    "build_discovery_index",
    "estimate_tokens",
    "has_tier_markers",
    "count_tier_markers",
    "SkillCompressor",
    "CompressionResult",
    "compress_file",
    "compress_directory",
    "SecurityScanner",
    "ScanResult",
    "Finding",
    "Severity",
    "scan_generated_output",
    "DependencyHealthReport",
    "DuplicateDep",
    "LicenseConflict",
    "OutdatedDep",
    "analyze_dependency_health",
    "Command",
    "PluginManifest",
    "build_commands",
    "build_plugin_manifest",
    "commands_prompt",
    "manifest_to_json",
    "manifest_to_markdown",
    "write_plugin",
    "generate_dependency_diagram",
    "generate_directory_diagram",
    "generate_call_flow_diagram",
    "generate_all_diagrams",
    "generate_erd_diagram",
    "generate_k8s_diagram",
    "generate_openapi_diagram",
    "Manifest",
    "ChapterEntry",
    "load_manifest",
    "save_manifest",
    "get_changed_files",
    "build_chapter_deps",
    "get_stale_chapters",
    "BlastRadiusResult",
    "CodeGraph",
    "Node",
    "Edge",
    "build_graph",
    "build_graph_from_workspace",
    "build_graph_v2",
    "get_blast_radius_v2",
    "is_test_file",
    "QueryResult",
    "query_callers",
    "query_callees",
    "query_imports",
    "ASTNode",
    "CFGNode",
    "CallEdgeInfo",
    "DFGEdge",
    "FileAnalysis",
    "FunctionAnalysis",
    "PDGEdge",
    "RepoAnalysis",
    "analyze_file",
    "analyze_repo",
    "format_analysis",
    "BehaviorIndex",
    "BehaviorMatch",
    "build_behavior_index",
    "format_search_results",
    "search_by_behavior",
    "CoverageFile",
    "CoverageReport",
    "auto_detect_and_parse",
    "detect_coverage_files",
    "parse_cobertura",
    "parse_coverage_py_json",
    "parse_jacoco",
    "parse_lcov",
    "render_coverage_markdown",
    "FileWatcher",
    "WatchEvent",
    "watch_docs",
    "import_docs",
    "fetch_npm_readme",
    "fetch_pypi_description",
    "fetch_github_docs",
    "AnalysisPrompt",
    "PROMPT_TYPES",
    "generate_prompts",
    "render_prompts_markdown",
    "write_individual_prompts",
    "RepoEntry",
    "CrossRepoMatch",
    "registry_add",
    "registry_remove",
    "registry_list",
    "registry_build",
    "registry_search",
    "format_registry_list",
    "format_cross_repo_results",
    "cross_repo_results_to_json",
]
